### ISSUE TITLE
A little bug in the output variables

### ISSUE THREAD

**Issue by yehia2221** [claranet/terraform-azurerm-db-mysql#1]
Thanks for this great model.

There is a little bug in the the output variable:

output "mysql_vnet_rule_ids" {
  value       = azurerm_mysql_virtual_network_rule.vnet_rules.*.ids
  description = "The list of all vnet rule resource ids"
}

The attribute ids does not exist. I thinks that it is just a misprinting error, the correct:
output "mysql_vnet_rule_ids" {
  value       = azurerm_mysql_virtual_network_rule.vnet_rules.*.id
  description = "The list of all vnet rule resource ids"
}

Thanks,

**Comment by Shr3ps** [comment]
Thanks for your issue!
This should have been fixed in tag/release v2.1.0

**Comment by yehia2221** [comment]
ok, thanks,

 The tag/release v2.1.0 is not yet pushed.

**Comment by rossifumax** [comment]
Hello @yehia2221,

Tag v2.1.0 is pushed now.

Thanks for your report!
